# It means that we need super level permissions
sudo: required
  - docker

  # Steps require befure running our test or deploy our project
  before_install:
    # The "." means the current project directory
    # -t means that I am taging my "image ID" with this name "juangom/docker-react"
    # You can use any name in the tag, but it is a con vention use the docker user name and the repository name
    - docker build -t juangom/docker-react -f Dockerfile.dev .